<?php 
  /* 
    Page Template: There's a javascript object that builds out all of the actual content. This is just a foreach that takes a simulated controller object and builds sections
TODO: give all image arrays alt text
  */ 
$slides = array(
//SLIDE 1
  array(
    'slide_bem' => 'classmates',
    'slide_title' => 'Classmates',
    'slide_content' => array(
      array(
        'identifier' => 'it-all-started',
        'content' => 'For Matt and Kate, it all started in a large lecture hall at MSU. Though told by a mutual acquaintance they were perfect for each other, they somehow managed to avoid eye contact even once for the entire semester.',
      ),
      array(
        'identifier' => 'final-day',
        'content' => 'On the final day of class, with nothing to lose, Kate decided to make first contact&hellip;over the internet&hellip;inviting Matt to a Cinco de Mayo party.',
      ),
    ),//content

    'slide_images' => array(
      array(
        'identifier' => 'matt-head',
        'path' => 'img/slide-1/matt-head.png',
      ),
      
      array(
        'identifier' => 'kate-head',
        'path' => 'img/slide-1/kate-head.png',
      ),
      
      array(
        'identifier' => 'class-scene',
        'path' => 'img/slide-1/class-scene.png',
      ),      
    ),//images
  ),//slide

//SLIDE 2
  array(
    'slide_bem' => 'partiers',
    'slide_title' => 'Partiers',
    'slide_content' => array(
      array(
        'identifier' => 'drunkenly-biked',
        'content' => 'On the chance of starting something special, <span class="tooltip" data-tooltip-title="Matt does not condone operation of bicycles while intoxicated">Matt drunkenly biked</span> across campus to attend the party. It was here that he realized he must not let this girl slip away.',
      ),
      array(
        'identifier' => 'foreshadowing',
        'content' => 'He had to see her again.',
      ),
    ),//content

    'slide_images' => array(
      array(
        'identifier' => 'little-flags',
        'path' => 'img/slide-2/banner.png',
      ),
      
      array(
        'identifier' => 'drunk-matt',
        'path' => 'img/slide-2/matt.png',
      ),
      
      array(
        'identifier' => 'kate-couch',
        'path' => 'img/slide-2/couch.png',
      ),

      array(
        'identifier' => 'bar-bg',
        'path' => 'img/slide-2/bar.png',
      ),
    ),//images
  ),//slide

//SLIDE 3
  array(
    'slide_bem' => 'roadies',
    'slide_title' => 'Roadies',
    'slide_content' => array(
      array(
        'identifier' => 'moved-home',
        'content' => 'So Kate moved home for the summer, and Matt stayed in East Lansing. Weekend after weekend, the two took turns finding convenient excuses to be in the other’s cities.',
      ),
      array(
        'identifier' => 'foreshadowing',
        'content' => 'A friendship grew to the like that Matt had never experienced before.',
      ),
    ),//content

    'slide_images' => array(
      array(
        'identifier' => 'beaumont',
        'path' => 'img/slide-3/beaumont.png',
      ),
      
      array(
        'identifier' => 'caulder',
        'path' => 'img/slide-3/caulder.png',
      ),
      
      array(
        'identifier' => 'el',
        'path' => 'img/slide-3/el.png',
      ),

      array(
        'identifier' => 'gr',
        'path' => 'img/slide-3/gr.png',
      ),

      array(
        'identifier' => 'michigan',
        'path' => 'img/slide-3/michigan.png',
      ),

      array(
        'identifier' => 'path1',
        'path' => 'img/slide-3/path1.png',
      ),
      array(
        'identifier' => 'path2',
        'path' => 'img/slide-3/path2.png',
      ),
      array(
        'identifier' => 'path3',
        'path' => 'img/slide-3/path3.png',
      ),
      array(
        'identifier' => 'path3',
        'path' => 'img/slide-3/path3.png',
      ),
      array(
        'identifier' => 'path4',
        'path' => 'img/slide-3/path4.png',
      ),
      array(
        'identifier' => 'path5',
        'path' => 'img/slide-3/path5.png',
      ),
      array(
        'identifier' => 'path6',
        'path' => 'img/slide-3/path6.png',
      ),
      array(
        'identifier' => 'path7',
        'path' => 'img/slide-3/path7.png',
      ),
      array(
        'identifier' => 'path8',
        'path' => 'img/slide-3/path8.png',
      ),
    ),//images
  ),//slide


//SLIDE 4
  array(
    'slide_bem' => 'the-talk',
    'slide_title' => 'The Talk',
    'slide_content' => array(
      array(
        'identifier' => 'stolen-thunder',
        'content' => 'So it was decided. On a weekend trip to Chicago, Matt would make this friendship a relationship, all he had to do was wait for the right moment…until of course Kate found the perfect moment herself—stealing Matt’s thunder.',
      ),
      array(
        'identifier' => 'foreshadowing',
        'content' => 'But no matter, this was the happiest Matt had ever been.',
      ),
    ),//content

    'slide_images' => array(
      array(
        'identifier' => 'background',
        'path' => 'img/slide-4/background.png',
      ),
      
      array(
        'identifier' => 'brick',
        'path' => 'img/slide-4/brick.png',
      ),
      
      array(
        'identifier' => 'kate',
        'path' => 'img/slide-4/kate.png',
      ),

      array(
        'identifier' => 'matt',
        'path' => 'img/slide-4/matt.png',
      ),
    ),//images
  ),//slide

//SLIDE 5
  array(
    'slide_bem' => 'happiness-graph',
    'slide_title' => ':D/T',
    'slide_content' => array(
      array(
        'identifier' => 'happiness-plus-plus',
        'content' => 'To Matt’s surprise, things just kept getting better! Every moment spent with Kate made Matt happier and happier.',
      ),
      array(
        'identifier' => 'foreshadowing',
        'content' => 'He was sure this trend couldn’t get any better.',
      ),
    ),//content

    'slide_images' => array(
      array(
        'identifier' => 'background',
        'path' => 'img/slide-5/background.png',
      ),
      
      array(
        'identifier' => 'clock-bg',
        'path' => 'img/slide-5/clock-bg.png',
      ),
      
      array(
        'identifier' => 'clock-face',
        'path' => 'img/slide-5/clock-face.png',
      ),

      array(
        'identifier' => 'clock-hand-hour',
        'path' => 'img/slide-5/clock-hand-hour.png',
      ),

      array(
        'identifier' => 'clock-hand-minute',
        'path' => 'img/slide-5/clock-hand-minute.png',
      ),

      array(
        'identifier' => 'dash-1',
        'path' => 'img/slide-5/dash-1.png',
      ),
      array(
        'identifier' => 'dash-2',
        'path' => 'img/slide-5/dash-2.png',
      ),
      array(
        'identifier' => 'dash-3',
        'path' => 'img/slide-5/dash-3.png',
      ),
      array(
        'identifier' => 'dash-4',
        'path' => 'img/slide-5/dash-4.png',
      ),
      array(
        'identifier' => 'dash-5',
        'path' => 'img/slide-5/dash-5.png',
      ),
      array(
        'identifier' => 'dash-6',
        'path' => 'img/slide-5/dash-6.png',
      ),
      array(
        'identifier' => 'dash-7',
        'path' => 'img/slide-5/dash-7.png',
      ),
      array(
        'identifier' => 'dash-8',
        'path' => 'img/slide-5/dash-8.png',
      ),
      array(
        'identifier' => 'dash-9',
        'path' => 'img/slide-5/dash-9.png',
      ),
      array(
        'identifier' => 'dash-10',
        'path' => 'img/slide-5/dash-10.png',
      ),
      array(
        'identifier' => 'dash-11',
        'path' => 'img/slide-5/dash-11.png',
      ),
      array(
        'identifier' => 'dash-12',
        'path' => 'img/slide-5/dash-12.png',
      ),
      array(
        'identifier' => 'dash-13',
        'path' => 'img/slide-5/dash-13.png',
      ),
      array(
        'identifier' => 'dash-14',
        'path' => 'img/slide-5/dash-14.png',
      ),

      array(
        'identifier' => 'happy-face',
        'path' => 'img/slide-5/happy-face.png',
      ),
    ),//images
  ),//slide

//SLIDE 6
  array(
    'slide_bem' => 'family-plus-plus',
    'slide_title' => 'Family++',
    'slide_content' => array(
      array(
        'identifier' => 'along-came-margot',
        'content' => 'Then along came Margot. Margot proved to be the finest addition to their little family Matt could hope for.',
      ),
      array(
        'identifier' => 'setup',
        'content' => 'He certainly couldn’t imagine anything that would make him happier&hellip;',
      ),
      array(
        'identifier' => 'foreshadowing',
        'content' => '&hellip;than making this last a lifetime.',
      ),
    ),//content

    'slide_images' => array(
      array(
        'identifier' => 'kate-head',
        'path' => 'img/slide-6/matt-head.png',
      ),
      
      array(
        'identifier' => 'matt-head',
        'path' => 'img/slide-6/matt-head.png',
      ),
      
      array(
        'identifier' => 'margot-head',
        'path' => 'img/slide-6/margot-head.png',
      ),

      array(
        'identifier' => 'margot-paw-left',
        'path' => 'img/slide-6/margot-paw-left.png',
      ),

      array(
        'identifier' => 'margot-paw-right',
        'path' => 'img/slide-6/margot-paw-right.png',
      ),
    ),//images
  ),//slide

//SLIDE 7
  array(
    'slide_bem' => 'city-bound',
    'slide_title' => 'City Bound',
    'slide_content' => array(
      array(
        'identifier' => 'graduation',
        'content' => 'Suddenly, the world was flipped upside down by some pesky business involving graduation. It was time to enter the real world.',
      ),
      array(
        'identifier' => 'foreshadowing',
        'content' => 'And so with both having dreams of living in Chicago and both knowing they couldn’t do it without each other, they packed their bags and headed for the next chapter.',
      ),
    ),//content

    'slide_images' => array(
      array(
        'identifier' => 'bean',
        'path' => 'img/slide-7/bean.png',
      ),
      
      array(
        'identifier' => 'car',
        'path' => 'img/slide-7/car.png',
      ),
      
      array(
        'identifier' => 'road',
        'path' => 'img/slide-7/road.png',
      ),

      array(
        'identifier' => 'skyscraper',
        'path' => 'img/slide-7/skyscraper.png',
      ),

      array(
        'identifier' => 'willis-tower',
        'path' => 'img/slide-7/willis-tower.png',
      ),
    ),//images
  ),//slide

);//slides

foreach( $slides as $slide ){
  $slideBem = $slide['slide_bem'];
  $slideTitle = $slide['slide_title'];
  $slidePs = $slide['slide_content'];
  $slideImgs = $slide['slide_images']
?>
  <section class="slide <?php echo $slideBem; ?>">
    <h1 class="slide__title"><?php echo $slideTitle; ?></h1>
    <?php foreach( $slidePs as $p ){ ?>
      <p class="<?php echo $slideBem . '__' . $p['identifier']; ?>"><?php echo $p['content']; ?></p>
    <?php } ?>
  
    <?php foreach( $slideImgs as $img ){ ?>
      <img class="<?php echo $slide['slide_bem'] . '__' . $img['identifier']; ?>" src="<?php echo $img['path']; ?>" alt="<?php echo $img['identifier']; ?>" />
    <?php } ?>
  </section>
<?php }//enforeach ?>