<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8">
	<title>Classmates to…mates?</title>
	<meta name="description" content="Once there were two young kids that went to Michigan State University, now they've gone and decided to marry.">
	<meta name="author" content="@joshDcomp, @mtthwbsh">

	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<!-- CSS
  ==============================================================================-->
	<link rel="stylesheet" href="base.css">
	<!-- Fonts
  ==============================================================================-->
  <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:900|Gentium+Basic:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
	<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

	<!-- Favicons
  ==============================================================================-->
	<link rel="shortcut icon" href="img/favicons/favicon.ico">
	<link rel="apple-touch-icon" href="img/favicons/apple-touch-icon.png">
	<link rel="apple-touch-icon" sizes="72x72" href="img/favicons/apple-touch-icon-72x72.png">
	<link rel="apple-touch-icon" sizes="114x114" href="img/favicons/apple-touch-icon-114x114.png">
</head>
<body>
  <div class="story_book">
  <div class="text">
        	
        	<h1>This experience was crafted by SASSy WP developer <a href="#" target="_blank">Joshua Compton</a>, and front-end juggernaut <a href="#" 
        	target="_blank">Matthew Bush</a>; accompanied by the gorgeous illustrations of <a href="#" target="_blank">Gabriel Cooper</a>.</h1>
	        
	        <h2>This is a <span>love</span> story.</h2>
        	
        	<h3>To: <span>Kate</span></h3>
        	<h3>From: <span>Matt</span></h3>
        	
        	<h4><a href="#" class="button">Enter</a></h4>
        	
        	</div>

  
    <?php include('covers/_front-cover.phtml'); ?>
    <?php include('pages/_page-factory.phtml'); ?>
    <?php include('covers/_colophon.phtml'); ?>
  </div><!-- .container -->
	<!-- SCRIPTS
  ==============================================================================-->
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
</body>
</html>