<?php
  /*
    * Page Template: There's a javascript object that builds out all of the
    * actual content. This is just a foreach that takes a simulated controller
    * object and builds sections

    * TODO: give all image arrays alt text
  */
  var slideBem = 'meet-up';
?>
<section class="slide <?php echo $slideBem; ?>">
    <h1 class="slide__title">Continue?</h1>
    <p class="<?php echo $slideBem; ?>__message">That brings us to July 16, 2013. Matt didn't think the story should end with a cliffhanger, so he told Kate to meet him at 635 W. Arlington Pl in Lincoln park, and asked a simple question&hellip;</p>
    <div class="<?php echo $slideBem; ?>__map-tooltip">
        <h2><a href="https://maps.google.com/maps?q=635+W.+Arlington,+in+Lincoln+Park&hl=en&sll=40.697488,-73.979681&sspn=0.930813,1.686401&hnear=635+W+Arlington+Pl,+Chicago,+Cook,+Illinois+60614&t=m&z=17">635 W. Arlington pl</a></h2>
    </div>
    <div class="<?php echo $slideBem; ?>__map-canvas"></div>
    <p class="meet-up__she-said-yes">She said yes!</p>
</section>
