<article class="story_book__colophon">
  <hgroup><h1>This is where we'll give credit to ourselves, talk about the tools we used, etc</h1></hgroup>
  
  <h2>Heroic collaborators</h2>
  <ul class="colophon__collab-list">
    <?php //Matt ?>
    <li class="colophon__collab-list__li">
      <a href="" class="collab-list__img-link"><img src="http://placehold.it/50x50" alt="" /></a>
      <a href="#_">Name Nameson</a>
    </li>
    <?php //Gabe ?>
    <li class="colophon__collab-list__li">
      <a href="" class="collab-list__img-link"><img src="http://placehold.it/50x50" alt="" /></a>
      <a href="#_">Name Nameson</a>
    </li>
    <?php //Josh ?>
    <li class="colophon__collab-list__li">
      <a href="" class="collab-list__img-link"><img src="http://placehold.it/50x50" alt="" /></a>
      <a href="#_">Name Nameson</a>
    </li>
  </ul>
  
  <h2>Tools Used</h2>
  <ul class="colophon__tools-list">
    <li><a href="#_">SASS</a></li>
    <li><a href="#_">Skeleton</a></li>
    <li><a href="#_">Emmet</a></li>
    <li><a href="">Coda</a></li>
  </ul>
  
  <h2>Design Notes</h2>
  <ul class="colophon__design-list">
    <li><a href="">Fonts</a></li>
  </ul>
  
  <aside>Congrats sir.</aside>
  
</article><!-- story_book__colophon -->
