<footer class="story_book__colophon">
  <hgroup><h1>This is where we'll give credit to ourselves, talk about the tools we used, etc</h1></hgroup>
    <h1>This experience was crafted by SASSy WP developer <a href="#" target="_blank">Josh Compton</a>, and front-end juggernaut <a href="#" 
    target="_blank">Matthew Bush</a>, accompanied by the gorgeous illustrations of <a href="#" target="_blank">Gabe Cooper</a>.</h1>

  <h2>Heroic Collaborators</h2>
  <ul class="colophon__collab-list">
    <?php //Matt ?>
    <li class="colophon__collab-list__li">
      <a href="http://mtthwbsh.com" target="_blank" class="collab-list__img-link"><img src="img/contributor-thumbs/matt.png" alt="" /></a>
      <a href="http://mtthwbsh.com" target="_blank">Matthew Bush</a>
    </li>
    <?php //Gabe ?>
    <li class="colophon__collab-list__li">
      <a href="http://gabecooper.com" target="_blank" class="collab-list__img-link"><img src="img/contributor-thumbs/gabe.jpg" alt="" /></a>
      <a href="http://gabecooper.com" target="_blank">Gabe Cooper</a>
    </li>
    <?php //Josh ?>
    <li class="colophon__collab-list__li">
      <a href="http://joshdcompton.com" target="_blank" class="collab-list__img-link"><img src="http://placehold.it/50x50" alt="" /></a>
      <a href="http://joshdcompton.com" target="_blank">Josh Compton</a>
    </li>
  </ul>
  
  <h2>Toolkit</h2>
  <ul class="colophon__tools-list">
    <li><a href="http://sass-lang.com/" target="_blank">SASS</a></li>
    <li><a href="http://www.getskeleton.com/" target="_blank">Skeleton</a></li>
    <li><a href="http://emmet.io/" target="_blank">Emmet</a></li>
    <li><a href="http://panic.com/coda/" target="_blank">Coda</a></li>
    <li><a href="http://incident57.com/codekit/" target="_blank">CodeKit</a></li>
  </ul>
  
  <h2>Design Notes</h2>
  <ul class="colophon__design-list">
    <li><a href="">Fonts</a></li>
  </ul>
  
  <aside>Congrats sir.</aside>
  
</footer><!-- story_book__colophon -->
