<footer class="story_book__colophon">
    <h1>This experience was crafted by:</h1>
    	
      <section>	
   	  <h2>Heroic Collaborators</h2>
	  <ul class="colophon__collab-list">
	    <?php //Matt ?>
	    <li class="colophon__collab-list__li--matt">
	      <a href="http://mtthwbsh.com" target="_blank" class="collab-list__img-link"><img src="img/contributor-thumbs/matt.png" alt="" />Matthew Bush</a>
	    </li>
	    <?php //Gabe ?>
	    <li class="colophon__collab-list__li--gabe">
	      <a href="http://gabecooper.com" target="_blank" class="collab-list__img-link"><img src="img/contributor-thumbs/gabe.png" alt="" />Gabe Cooper</a>
	    </li>
	    <?php //Josh ?>
	    <li class="colophon__collab-list__li--josh">
	      <a href="http://joshdcompton.com" target="_blank" class="collab-list__img-link"><img src="img/contributor-thumbs/josh.png" alt="" />Josh Compton</a>
	    </li>
	  </ul>
      </section>
	  
	  <section>
	  <h2>Toolkit</h2>
	  <ul class="colophon__tools-list">
	    <li><a href="http://sass-lang.com/" target="_blank">SASS</a></li>
	    <li><a href="http://www.getskeleton.com/" target="_blank">Skeleton</a></li>
	    <li><a href="http://emmet.io/" target="_blank">Emmet</a></li>
	    <li><a href="http://panic.com/coda/" target="_blank">Coda</a></li>
	    <li><a href="http://incident57.com/codekit/" target="_blank">CodeKit</a></li>
	  </ul>
	  </section>
	  
	  <section>
	  <h2>Design Notes</h2>
	  <ul class="colophon__design-list">
	    <li><a href="http://www.google.com/fonts#UsePlace:use/Collection:Source+Sans+Pro:200,300,400,600,700,900,200italic,300italic,400italic,600italic,700italic|Gentium+Basic:400,700,400italic,700italic" target="_blank">Fonts</a>
	    </li>
	  </ul>
	  </section>
  
</footer><!-- story_book__colophon -->
