<header class="story_book__intro">
        
  
  <h1 class="story_book__intro__header">This is a <span class="story_book__intro__header--love">love</span> story.</h1>
  
  <h2 class="story_book__intro__to-from"><span class="story_book__intro__to-from--label">To:</span> <span class="story_book__intro__to-from--name">Kate</span></h2>
  <h2 class="story_book__intro__to-from"><span class="story_book__intro__to-from--label">From:</span> <span class="story_book__intro__to-from--name">Matt</span></h2>
  
  <a href="#" class="button story_book__open">BEGIN</a>
        
</header><!-- .story_book__intro -->