<header class="story_book__intro">
        
  
  <h1 class="story_book__intro__header">
    <span class="story_book__intro__header--preamble">This is</span>
    <span class="story_book__intro__header--preamble">a love</span> 
    <span class="story_book__intro__header--story">story</span>
  </h1>
  
  <h2 class="story_book__intro__to-from kate"><span class="story_book__intro__to-from--label">To:</span> <span class="story_book__intro__to-from--name">Kate</span></h2>
  <h2 class="story_book__intro__to-from matt"><span class="story_book__intro__to-from--label">From:</span> <span class="story_book__intro__to-from--name">Matt</span></h2>
  
  <p class="button story_book__open">Begin</p>
  
  <p class="story_book__instructions">To start, click ‘Begin’, and use your right arrow key or the space bar to advance.</p>
        
</header><!-- .story_book__intro -->