<?php 
  /* 
    Page Template: There's a javascript object that builds out all of the actual content. This is just a foreach that takes a simulated controller object and builds sections
TODO: give all image arrays alt text
  */ 
  $slideBem = 'meet-up';

    $dayOfTstamp = strtotime('2013-07-16');    
    $date = date('Y-m-d', $dayOfTstamp);
    $now = date('Y-m-d');
  
  $dateString = ( $now == $date )
    ? 'today, '
    : '';
?>
<section class="slide <?php echo $slideBem; ?>">
    <h1 class="slide__title">Continue?</h1>
    <p class="<?php echo $slideBem; ?>__message">That brings us to <?php echo $dateString; ?> July 16, 2013. The story doesn’t have to end here. to continue, please meet at the following location in a timely fashion.</p>
    <div class="<?php echo $slideBem; ?>__map-canvas"></div>
</section>
